### PR TITLE
Fix(sessions_manager): change "enoght" to "enough"

### LINKED ISSUE #484: Typo: `enoght` → `enough`
There's a typo in `/node/src/actors/session_manager/mod.rs` at line `188`:

https://github.com/witnet/witnet-rust/blob/dc518f1ec3dae4dcdea28c046924e51ed0233c48/node/src/actors/sessions_manager/mod.rs#L188

`enoght` → `enough`

### PR DESCRIPTION
**Pull request by orbweaver-**
Fixes #484 typo

### CODE REVIEW

**Comment by aesedepece** [comment]
@orbweaver- thanks for joining the Witnet community and doing your first contribution!

Commit messages need to abide by the [conventional commits specification](https://www.conventionalcommits.org/en/v1.0.0-beta.2/), and references to the original issue are not needed as we use use ZenHub for that. A example for this issue could be:
```
fix(sessions_manager): change "enoght" for "enough"
```
Btw, feel free to drop by the [Witnet community on Discord](https://discord.gg/X4uurfP) at any time to discuss any future contributions and learn more about the project :D

**Comment by orbweaver-** [comment]
@aesedepece Ok, the commit message has been changed accordingly

**Comment by aesedepece** [comment]
Great @orbweaver-, one last thing—all commits need to be [verified with your PGP signature](https://help.github.com/en/articles/signing-commits) :sweat_smile:

**Comment by orbweaver-** [comment]
@aesedepece Sorry, new computer. Hadn't set that up yet. Should be good now

**Comment by aesedepece** [comment]
@orbweaver- Thanks for verifying your commit! I'll be happy to merge this PR as soon as the tests pass :+1:

**Pull request merged**
