### PR TITLE
fix(jsonrpc): change spammy log level

### PR DESCRIPTION
**Pull request by Kielek**

### CODE REVIEW

**Comment by aesedepece** [comment]
@Kielek thanks for joining the Witnet community and doing your first contribution!

Please remove the reference to the original issue from the commit header of your PR. You can rather move that reference to the body of the message:
```
fix(jsonrpc): change spammy log level

Close #567
```

I'll be happy to positively review your PR once that's done :D

**Comment by Kielek** [comment]
@aesedepece, commit message fixed

**Comment by Kielek** [comment]
@aesedepece, if you are ok, please merge. I do not have permissions.

**Comment by aesedepece** [comment]
Merged as be44189a2fabc2e4cdc4d09e4f6eb590aabf92ed. Thanks @Kielek !

**Pull request closed without merging**
