### PR TITLE
chore(cargo): move "just" to dev-dependencies

### LINKED ISSUE #575: `just` should only be a dev-dependency in Cargo.toml
We should move `just` out of `dependencies` in Cargo.toml and rather put it in the `dev-dependencies section` (which doesn't exist yet):

```toml
[dev-dependencies]
just = "0.3.13"
```
A pull request solving this issue should also update Cargo.lock so it is consistent with the new configuration.

### PR DESCRIPTION
**Pull request by satyaki-mallick**
fix #575

### CODE REVIEW

**Comment by satyaki-mallick** [comment]
I need not change the Cargo.lock file as the old configs automatically picked up the changes.

**Comment by aesedepece** [comment]
Merged as 42b316287b2b10574d3f1a8c1c2a0c1c28261422. Thanks @satyaki-mallick ! :smiley:

**Comment by satyaki-mallick** [comment]
Hi @aesedepece , any way of getting the gitcoin reward ..?  smiley

**Comment by aesedepece** [comment]
@satyaki-mallick Just tell me your gitcoin username and next time make sure you pledge the work on gitcoin :wink:

**Comment by satyaki-mallick** [comment]
Positively @aesedepece  :)
My gitcoin is connected through git-hub. So it is the same username, **satyaki-mallick**

**Pull request closed without merging**
