### PR TITLE
Rad replace separators

### PR DESCRIPTION
**Pull request by aesedepece**
Supersedes #1610

### CODE REVIEW

**Comment by tmpolaczyk** [comment]
I think this only applies to RadonMaps, so we need to repeat the same code in RadonArray for the operators ArrayGetInteger and ArrayGetFloat, and also in RadonString for operators StringAsFloat and StringAsInteger.

**Comment by aesedepece** [comment]
> I think this only applies to RadonMaps, so we need to repeat the same code in RadonArray for the operators ArrayGetInteger and ArrayGetFloat, and also in RadonString for operators StringAsFloat and StringAsInteger.

True

**Comment by aesedepece** [comment]
This grew a bit. Sorry not sorry :stuck_out_tongue_winking_eye:

**Comment by aesedepece** [comment]
Due to the latest changes, this should no longer be a breaking change.

**Comment by tmpolaczyk** [comment]
To make this change even less breaking, would it be possible to active it after a certain block number? Otherwise I think that if someone uses one of the new operators in the tally stage, it can cause old nodes to reject that block and create a hard fork.

**Comment by aesedepece** [comment]
> To make this change even less breaking, would it be possible to active it after a certain block number? Otherwise I think that if someone uses one of the new operators in the tally stage, it can cause old nodes to reject that block and create a hard fork.

Sounds reasonably paranoid :ok_hand:

**Comment by aesedepece** [comment]
I will rebase this on top of #1789 after hard fork date is decided (#1791).

**Comment by aesedepece** [comment]
@tmpolaczyk on second thought, getting knowledge of current epoch at the operator level inside the radon executor would require overly disruptive changes to the code that would add complexity, reduce clarity and serve no other purpose than specifically this.

**Comment by tmpolaczyk** [comment]
Yes, it's hard to implement because this is the first change to RADON in mainnet. I think that eventually we will need to add that logic anyway, as we keep improving RADON. But if it's too much overhead for now, then I prefer to delay this PR until we have some major RADON 2.0 update, to avoid delaying the release because of this.

**Comment by aesedepece** [comment]
Let's do that.

**Comment by aesedepece** [comment]
This should be safe to adopt now that we have TAPI. I'll close this PR and open a new issue.

**Pull request closed without merging**
