### PR TITLE
feat(node): allow using the node's JSON-RPC API over any transport

### PR DESCRIPTION
**Pull request by aesedepece**
This essentially replaces all the business logic in the JSON-RPC actor with an instance of `WittyMultiServer` , and allows using all the existing JSON-RPC methods over TCP, HTTP and WebSockets at the same time.

Usage
```toml
[jsonrpc]
# Enables or disables the JSON-RPC server altogether. This is needed for using the CLI methods of the node.
enabled = true
# The addresses (IP and port) which the JSON-RPC server binds to.
# WARNING: these should be kept to a local, private address (e.g. 127.0.0.1) to prevent any device in your local network
# (and potentially, the internet) from messing with your JSON-RPC server.
# JSON-RPC over plain TCP (required for CLI usage). Set `enabled` above to `false` to disable.
tcp_address = "127.0.0.1:21338"
# JSON-RPC over HTTP. Remove the line to disable it.
http_address = "127.0.0.1:21339"
# JSON-RPC over WebSockets. Remove the line to disable it.
ws_address = "127.0.0.1:21340"

```

This change is 100% backwards compatible (takes into account old settings and stuff).

Tasklist:
- [x] Create `witty-jsonrpc`  library
- [x] Add support for TCP
- [x] Add support for WebSockets
- [x] Add support for HTTP
- [x] Actix compatibility
- [x] Publish library on Crates.io https://crates.io/crates/witty-jsonrpc
- [x] Integrate library into witnet-rust
- [x] Fix tests (currently, they never finish because of Actix shenanigans) 
- [x] Allow configuring JSON-RPC transports through `witnet.toml`
- [x] Clippy, etc.
- [x] Add documentation to library
- [x] Push library to GitHub

In the future, we may want to leverage this same approach to multi-transports JSON-RPC interfaces on other components, like the wallet or the bridge.

solve #2375

### CODE REVIEW

**Comment by Tommytrg** [comment]
I'm trying to test this PR but I can only run the node without errors using the following configuration:
```toml
[jsonrpc]
enabled = true
server_address = "127.0.0.1:1235"
```

If I use the new options instead I get an error:
```toml
[jsonrpc]
enabled = true
tcp_address = "127.0.0.1:21338"
http_address = "127.0.0.1:21339"
ws_address = "127.0.0.1:21340"
```

``` 
cargo run -- -c witnet_02.toml node server
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
warning: the following packages contain code that will be rejected by a future version of Rust: quick-xml v0.22.0, rustc-serialize v0.3.24
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running `target/debug/witnet -c witnet_02.toml node server`
Loading config from: witnet_02.toml
Setting log level to: INFO, source: Config
[2023-06-07T10:47:16Z INFO  witnet_config::config] The default unproxied HTTP transport for retrieval is enabled.
[2023-06-07T10:47:16Z INFO  witnet_node::actors::peers_manager::actor] Adding the following peer addresses from config: [127.0.0.1:21339]
[2023-06-07T10:47:16Z INFO  witnet_node::actors::connections_manager] P2P server has been started at 0.0.0.0:21338
[2023-06-07T10:47:16Z INFO  witnet_node::actors::epoch_manager] Checkpoint zero timestamp: 1610556418, checkpoints period: 10
[2023-06-07T10:47:16Z INFO  witnet_node::actors::json_rpc::server] HTTP JSON-RPC interface will listen on 127.0.0.1:21339
[2023-06-07T10:47:16Z INFO  witnet_node::actors::json_rpc::server] TCP JSON-RPC interface will listen on 127.0.0.1:21338
[2023-06-07T10:47:16Z INFO  witnet_node::actors::json_rpc::server] WebSockets JSON-RPC interface will listen on 127.0.0.1:21340
thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /home/tommy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.0/src/runtime/blocking/shutdown.rs:51:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2023-06-07T10:47:16Z ERROR witnet_node::utils] Panic in JsonRpcServer, shutting down system
Error: Non-zero exit code: 1
pure virtual method called
terminate called without an active exception
[1]    73993 IOT instruction (core dumped)  cargo run -- -c witnet_02.toml node server
```

**Comment by aesedepece** [comment]
Classic _"but it works for me"_ situation: :rofl: 
```
cargo run -- -c witnet_02.toml node server
    Finished dev [unoptimized + debuginfo] target(s) in 0.29s
warning: the following packages contain code that will be rejected by a future version of Rust: quick-xml v0.22.0, rustc-serialize v0.3.24
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 795`
     Running `target/debug/witnet -c witnet_02.toml node server`
Loading config from: witnet_02.toml
Setting log level to: INFO, source: Config
[2023-06-07T16:12:56Z INFO  witnet_config::config] The default unproxied HTTP transport for retrieval is enabled.
[2023-06-07T16:12:56Z INFO  witnet_node::actors::peers_manager::actor] Adding the following peer addresses from config: [127.0.0.1:21339]
[2023-06-07T16:12:56Z INFO  witnet_node::actors::connections_manager] P2P server has been started at 0.0.0.0:21338
[2023-06-07T16:12:56Z INFO  witnet_node::actors::epoch_manager] Checkpoint zero timestamp: 1610556418, checkpoints period: 10
[2023-06-07T16:12:56Z INFO  witnet_node::actors::json_rpc::server] TCP JSON-RPC interface will listen on 127.0.0.1:1235
[2023-06-07T16:12:57Z INFO  witnet_node::storage_mngr] Configured RocksDB as the storage backend
[2023-06-07T16:12:57Z INFO  witnet_node::actors::chain_manager::actor] Node identity / address: twit1m8259w3s2v7uv0se8j4q7jhzx00recm749hd7d
[2023-06-07T16:12:57Z INFO  witnet_node::actors::chain_manager::actor] Current ChainState CheckpointBeacon: epoch (0), hash_block (00000000000000000001000000000000000000007769746e65742d302e372e30)
[2023-06-07T16:12:57Z INFO  witnet_node::actors::chain_manager::actor] Genesis block successfully created. Hash: a0b6496d8de53c5998b89a72bb233c600822e14a3b6709154553c74f90604f23
```

**Comment by aesedepece** [comment]
This has been rebased on top of #2381. @Tommytrg you should be able to try it again!

**Review by Tommytrg — APPROVED** [review]
I've been able to use the JSON-RPC over TCP, HTTP and WebSockets

**Pull request merged**
