### PR TITLE
feat(docker-compose): add getVersion wrapper

### PR DESCRIPTION
**Pull request by bertux**

### CODE REVIEW

**Comment by aesedepece** [comment]
I may be wrong, but I think that the correct command for getting the version is:
```console
witnet node --version
```

**Comment by bertux** [comment]
I've copied what I was using before on my node but you are right it doesn't work anymore and now it's needed to use --version so I'm correcting it, thank you to have seen it.

**Comment by aesedepece** [comment]
@bertux This is one trick I normally do for running the same command on all nodes:
```console
docker ps | grep witnet-rust | cut -d' ' -f1 | parallel docker exec {} ./witnet node --version
```

Needless to say that it has `parallel` as a dependency :sweat_smile:

**Comment by bertux** [comment]
> @bertux This is one trick I normally do for running the same command on all nodes:
> 
> ```
> docker ps | grep witnet-rust | cut -d' ' -f1 | parallel docker exec {} ./witnet node --version
> ```
> 
> Needless to say that it has `parallel` as a dependency 😅

Thank you for this trick, I will add it to the script, and it would be even better to be able to use Docker tags to select the docker containers running witnet-rust

**Pull request merged**
