### PR TITLE
fix(json_rpc): change logging level for NewBlock messages

### PR DESCRIPTION
**Pull request by satyaki-mallick**

### CODE REVIEW

**Comment by satyaki-mallick** [comment]
fix(jsonrpc): changed log level

Close #567

**Comment by aesedepece** [comment]
Hi @satyaki-mallick, thanks for joining the Witnet community and doing your first contribution!

A couple of things:
- For your commits to be merged, they need to be [verified with your PGP signature](https://help.github.com/en/articles/signing-commits).
- It looks like @kielek was already working on this (see #580)

**Comment by satyaki-mallick** [comment]
HI. I added a commit with GPG signing.
Ya, I saw his work now. if his work gets approved, you can reject my pull request. No problem.

**Comment by aesedepece** [comment]
Closing this in favor of be44189a2fabc2e4cdc4d09e4f6eb590aabf92ed (#580).

**Pull request closed without merging**
