### PR TITLE
fix(wallet): fix show transactions after resync

### LINKED ISSUE #1818: [Wallet] Wallet only shows genesis transactions after resync
Steps to reproduce:

* Unlock a synced wallet with some transactions from the genesis block and some transactions from a later block
* Press resync button
* After it shows the genesis transactions, close the wallet
* Unlock the wallet again and wait
* The wallet will sync but only the genesis transactions will be shown.

### PR DESCRIPTION
**Pull request by mariocao**
Closes #1818

- Removes `resynchronization` flag
- Reuses a `needs_indexing` flag in `handle_block` function (single entry point for sync, resync and new block from node)
- Updates tests

### CODE REVIEW

**Comment by clbartoli** [comment]
When stopping the wallet while resyncing some of the balances are shown as  unconfirmed even if they were already confirmed. This could happen because by the time the resync was stopped those balances were not yet confirmed

image

**Comment by mariocao** [comment]
> When stopping the wallet while resyncing some of the balances are shown as unconfirmed even if they were already confirmed. This could happen because by the time the resync was stopped those balances were not yet confirmed

Definitely there is something weird with the balances! :smile: I will check how related it is to the issue https://github.com/witnet/witnet-rust/issues/1836

**Comment by mariocao** [comment]
After discussing and debugging with @lrubiorod and @clbartoli we found out the following issues:
 - The wallet is not tracking the available balance while synchronizing (issue #1836)
 - The wallet is not handling well "double" synchronization after unlocking the wallet for a second time (issue #1849)
 - Sometimes Sheikah goes back to the wallet list and ask to unlock wallet (despite being already unlocked) (issue https://github.com/witnet/sheikah/issues/1644)

**Review by lrubiorod — APPROVED** [review]

**Comment by aesedepece** [comment]
I'm trying this

**Review by aesedepece — APPROVED** [review]
It works!

**Pull request merged**
