### PR TITLE
feat(config): add initial difficulty as a consensus constant

### LINKED ISSUE #1345: Add an initial difficulty in the consensus constants
Currently we have an initial difficulty in the code as a patch for Testnet 0.9.0-c. We should have this difficulty as a parameter in the ConsensusConstants

### PR DESCRIPTION
**Pull request by lrubiorod**
Close #1345

### CODE REVIEW

**Comment by aesedepece** [comment]
We may apply something like this to all config settings that are expressing duration:

```rust
    #[partial_struct(serde(
        default,
        deserialize_with = "from_secs",
        rename = "initial_difficulty_duration"
    ))]
```

**Comment by lrubiorod** [comment]
> We may apply something like this to all config settings that are expressing duration:
> 
> ```rust
>     #[partial_struct(serde(
>         default,
>         deserialize_with = "from_secs",
>         rename = "initial_difficulty_duration"
>     ))]
> ```
I called duration, but is the number of epochs... Should we use another less misleading name?

**Comment by aesedepece** [comment]
I'd try to be explicit about what the unit of measure is.

**Comment by tmpolaczyk** [comment]
Let's name it "proof_of_work_epochs" :P

**Comment by tmpolaczyk** [comment]
Remove ignore from test in validations/src/validations.rs:

    // FIXME: remove this hack

**Comment by tmpolaczyk** [comment]
A few things that I would like to see documented somewhere:

* initial_difficulty ignores the backup factor. So if initial_difficulty = 1000 and the backup factor is 8, the probability to mine a block will be 1/1000 and not 8/1000

* epochs_with_initial_difficulty includes the epoch that it is set to. So if epochs_with_initial_difficulty = 1000, the block for epoch 1000 will also have the initial difficulty. The first block without initial difficulty will be the block for epoch 1001. This also means that setting epochs_with_initial_difficulty = 0 will keep this feature enabled for epoch 0, but that shouldn't be an issue because the block for epoch 0 is the genesis block, and so it follows a different validation.

**Pull request merged**
