### PR TITLE
feat(bridge): add skip_first config param to allow skipping requests

### LINKED ISSUE #2320: Populate local database from certain query id set as config parameter

### PR DESCRIPTION
**Pull request by tmpolaczyk**
Close #2320

### CODE REVIEW

**Review by guidiaz — CHANGES_REQUESTED** [review]
It works perfectly. However, we need to change the version tag to something like "1.5.4.1" as to make automated docker image construction and publishing work properly.

**Comment by aesedepece** [comment]
> It works perfectly. However, we need to change the version tag to something like "1.5.4.1" as to make automated docker image construction and publishing work properly.

Not strictly, I think we can just delete the existing release on DockerHub and then merge it.

**Comment by tmpolaczyk** [comment]
I would prefer a separate PR for version bumps anyway, as that shouldn't block this PR.

**Comment by guidiaz** [comment]
> > It works perfectly. However, we need to change the version tag to something like "1.5.4.1" as to make automated docker image construction and publishing work properly.
> 
> Not strictly, I think we can just delete the existing release on DockerHub and then merge it.

@aeweda ??

**Comment by guidiaz** [comment]
> Not strictly, I think we can just delete the existing release on DockerHub and then merge it.

Perhaps in this occasion, but imagine 1.5.4 image was already been used in all testnets and mainnets and we wanted to only deploy a new binary release into (a subset of) testnets.

**Comment by aesedepece** [comment]
> > Not strictly, I think we can just delete the existing release on DockerHub and then merge it.
> 
> Perhaps in this occasion, but imagine 1.5.4 image was already been used in all testnets and mainnets and we wanted to only deploy a new binary release into (a subset of) testnets.

We can always docker pull on the hosts where we need the latest one, or even refer the images by their hash.

In any case, the thing here is that CI now enforces consistency between the main witnet-rust crate and this one, so we can't do anything exotic with the versions. 

We can however make a 1.5.5 release of everything. It's all automated, so not a big deal.

**Comment by aeweda** [comment]
> > It works perfectly. However, we need to change the version tag to something like "1.5.4.1" as to make automated docker image construction and publishing work properly.
> 
> Not strictly, I think we can just delete the existing release on DockerHub and then merge it.

this would be a problem as it wouldn't force a rolling update / repull unless the version actually changes


> > > Not strictly, I think we can just delete the existing release on DockerHub and then merge it.
> > 
> > 
> > Perhaps in this occasion, but imagine 1.5.4 image was already been used in all testnets and mainnets and we wanted to only deploy a new binary release into (a subset of) testnets.
> 
> We can always docker pull on the hosts where we need the latest one, or even refer the images by their hash.
> 
> In any case, the thing here is that CI now enforces consistency between the main witnet-rust crate and this one, so we can't do anything exotic with the versions.
> 
> We can however make a 1.5.5 release of everything. It's all automated, so not a big deal.

i would go with 1.5.5 version release as we can't really go into servers one by one to do a docker pull
however if we are gonna standardize it this way, let me and i can make the deployment of the bridge automated with a new tag push

**Comment by tmpolaczyk** [comment]
Setting the version of `witnet-centralized-ethereum-bridge` to 1.5.5-rc1 results in this error in the script that checks version compatibility:

Version of subcrate "bridges/centralized-ethereum" (futures-util = { 0.3.8, features = ["compat"] }) does not match that of main crate (1.5.4)

**Review by guidiaz — APPROVED** [review]

**Comment by Tommytrg** [comment]
> We can however make a 1.5.5 release of everything. It's all automated, so not a big deal.

The main problem we have with releasing a new version of `witnet-rust` every time we release a new version of the bridge is we'll tweet and announce irrelevant releases from the miner's perspective and make unnecessary noise.

A recap of all the different options we have discussed until now are:
1. Release the bridge together with the node
    
    ##### Pros
    - The easiest way to release it	
	
    ##### Cons
    - Every time we release a new witnet-rust release, we publish a tweet and a bridge release is irrelevant from the miner's perspective.


2. Release the bridge and the node independently
	
    2.1 Move the bridge to its repository
      ##### Pros
      - We don't have to change any actions in witnet-rust or modify the automatic announcements
      ##### Cons
      - To do it, we have to create a new repo and completely decouple the bridge from witnet-rust 
      - We need to keep track of compatible versions between witnet-rust and the bridge 

    
   2.2 Release the bridge and the node independently in the same repo
 
	##### Pros
    - We don't need to create a new repo and dedicate development effort
 
	##### Cons
    - We need to keep track of compatible versions between witnet-rust and the bridge
    - We need to change the action that triggers a release announcement
 
In this, I suggest releasing the bridge and the node altogether. Apparently, this is a common strategy in monorepos, for example, Vue (https://github.com/vuejs/vue/releases) or Vercel (https://github.com/vercel/vercel)

To follow this strategy, we will need to stop the Zapier trigger and update it only to publish an announcement when a change is made in the protocol.

**Pull request merged**
