### PR TITLE
docs: update documentation links

### PR DESCRIPTION
**Pull request by igorline**
Updating contributing and systemd documentation links

To be merged after https://github.com/witnet/documentation/pull/36/ is merged

### CODE REVIEW

**Comment by bertux** [comment]
> Sorry for the delay.

now that @aesedepece has approved these changes, does it mean the wait is over ?
@igorline do we wait for someone specifically to merge ?

**Comment by igorline** [comment]
I don't have the permissions in this repo. But I believe it should have been merged already :)
Thank you @bertux

**Comment by bertux** [comment]
> I don't have the permissions in this repo. But I believe it should have been merged already :)
> Thank you @bertux

@igorline your branch is 3 commits behind witnet:master, can you rebase it yourself so I can merge it for you or should I rebase it myself locally first ?

**Comment by bertux** [comment]
I have managed to rebase it locally and merge it locally in master branch but when I try to push I have this error 
git push
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.25 KiB | 638.00 KiB/s, done.
Total 5 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
To github.com:witnet/witnet-rust.git
 ! [remote rejected]   master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:witnet/witnet-rust.git'
@aesedepece any idea about that ? maybe you should merge it instead of me.

**Comment by igorline** [comment]
@bertux I rebased it. In sync with main repo now.
But I believe you could just squash it or rebase and merge using github ui as it didn't had any conflicts.

**Pull request merged**
