### PR TITLE
feat(brigde): read config from env

### LINKED ISSUE #2231: Bridge: read config from environment
In the bridge, reading configuration from the environment will be much more convenient when trying to automate deployment of chain integration stacks.

### PR DESCRIPTION
**Pull request by tmpolaczyk**
Close #2231

Untested because that would require creating many environment variables. Environment variable format:

```
WITNET_CENTRALIZED_ETHEREUM_BRIDGE_WITNET_JSONRPC_ADDR="127.0.0.1:21338"
```

The default behavior is not changed, to read config from environment users need to pass a `--env` flag.

### CODE REVIEW

**Comment by aesedepece** [comment]
@guidiaz how do you think we should go about testing this one? Thanks!

**Comment by guidiaz** [comment]
> @guidiaz how do you think we should go about testing this one? Thanks!

Let's test w/ just one operational testnet stack: 
- Polygon Testnet

**Comment by guidiaz** [comment]
it would be nice to add an .env.example file to this repo, containing all expected env vars

**Comment by guidiaz** [comment]
testing w/ these env vars:
```
# adjustable params
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_ETH_ACCOUNT: "0x8c49CAfC4542D9EA9107D4E48412ACEd2A68aA77"
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_NUM_CONFIRMATIONS: 8
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_GAS_LIMITS_REPORT_RESULT: 3000000
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_WRB_CONTRACT_ADDR: "0x58D8ECe142c60f5707594a7C1D90e46eAE5AF431"
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_WITNET_JSONRPC_ADDR: "10.5.1.4:21338"
      # not-to-be-changed params
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_DB_PATH: "data/polygon_goerli"
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_ETH_CLIENT_URL: "http://gateway:8535"
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_MAX_RESULT_SIZE: 100
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_REQUEST_EXAMPLE_CONTRACT_ADDR: "" # "0xEaA9e7Ea612b169f5b41cfF86dA6322f57264a19"
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_WITNET_TESTNET: "false"
      # timing params
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_DR_TX_UNRESOLVED_TIMEOUT_MS: "600_000"
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_ETH_CONFIRMATION_TIMEOUT_MS: "900_000"
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_ETH_NEW_DR_POLLING_RATE_MS: "45_000"
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_MAX_DR_VALUE_NANOWITS: "100_000_000_000"
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_WIT_TALLY_POLLING_RATE_MS: "45_000"
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_WIT_DR_SENDER_POLLING_RATE_MS: "45_000"
```

**Review by guidiaz — CHANGES_REQUESTED** [review]
apparently, the envy lib doesn't support nested config sections, interpreting the `[gas limits]` and `[storage]` toml sections as unsupported hashmaps

**Comment by tmpolaczyk** [comment]
@guidiaz added a workaround, now these variables can be set like:

```
WITNET_CENTRALIZED_ETHEREUM_BRIDGE_GAS_LIMITS="post_data_request = 10_000\nreport_result = 20_000"
WITNET_CENTRALIZED_ETHEREUM_BRIDGE_STORAGE="db_path = \".witnet\""
```

The format of the nested variables is TOML.

**Comment by guidiaz** [comment]
It works by adapting values to this:
```
      # adjustable params
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_ETH_ACCOUNT: "0x8c49CAfC4542D9EA9107D4E48412ACEd2A68aA77"
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_GAS_LIMITS: "report_result = 3_000_000"
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_NUM_CONFIRMATIONS: 8
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_WITNET_JSONRPC_ADDR: "10.5.1.4:21338"
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_WRB_CONTRACT_ADDR: "0x58D8ECe142c60f5707594a7C1D90e46eAE5AF431"
      # not-to-be-changed params
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_ETH_CLIENT_URL: "http://gateway:8535"
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_MAX_DR_VALUE_NANOWITS: 100000000000 # 1 WIT
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_MAX_RESULT_SIZE: 100 # 100 bytes
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_REQUEST_EXAMPLE_CONTRACT_ADDR: "0xEaA9e7Ea612b169f5b41cfF86dA6322f57264a19"
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_STORAGE: "db_path = \"data/polygon_goerli\""
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_WITNET_TESTNET: "false"
      # timing params
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_DR_TX_UNRESOLVED_TIMEOUT_MS: 600000  # 10 min
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_ETH_CONFIRMATION_TIMEOUT_MS: 900000  # 15 min 
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_ETH_NEW_DR_POLLING_RATE_MS: 45000    # 45 secs
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_WIT_TALLY_POLLING_RATE_MS: 45000     # 45 secs
      WITNET_CENTRALIZED_ETHEREUM_BRIDGE_WIT_DR_SENDER_POLLING_RATE_MS: 45000 # 45 secs
```

**Review by aesedepece — APPROVED** [review]

**Review by guidiaz — APPROVED** [review]

**Pull request merged**
