### PR TITLE
Filter out 0.0.0.0 "unspecified" address when adding new peer addresses

### LINKED ISSUE #282: Don't accept 0.0.0.0 as peer address
When processing peers addresses lists, any `0.0.0.0` address should be dropped, not stored. This would reduce the failed connections ratio and speed up the bootstrapping process.

### PR DESCRIPTION
**Pull request by aesedepece**
Fix #282

### CODE REVIEW

**Comment by tmpolaczyk** [comment]
The standard library already provides some of these methods: `is_unspecified` and `is_loopback`, but the `is_global` method is not stable so we can implement it ourselves.

https://doc.rust-lang.org/std/net/enum.IpAddr.html

**Comment by aesedepece** [comment]
Oh my LOL.

**Comment by tmpolaczyk** [comment]
No, wait, https://doc.rust-lang.org/std/net/struct.Ipv4Addr.html provides the missing methods, you can safely remove most of the logic from this PR

**Comment by aesedepece** [comment]
Past-testnet, switchable `loopback` and `global` filters may be added.

**Pull request merged**
